---
title: "Analyses of swisscom data"
subtitle: "Grid eda"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       jsonlite, 
       # DT, 
       sf, tmap)

tmap_mode("view")

# import::from("sjmisc", "frq")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Ancillary data

## Municipality boundaries 

```{r}
st_gg21 <- read_rds("data/swisstopo/st_gg21.Rds")
```

Area of interest is **Chansy** to define `x`  
- Postal code `1284`
- SFOS number	`6611`

And **Chiasso** to define `y`  
- Postal code `6830`
- SFOS number	`5250`

```{r}
st_gg21 %>% 
  filter(GMDNR %in% c(6611, 5250)) %>% 
  st_geometry() %>% 
  qtm(borders = "red", fill = NULL)
```

```{r}
chansy <- read_rds("data/grid/chansy.Rds")
```

```{r}
chansy %>% 
  st_geometry() %>% 
  qtm(borders = "red", fill = NULL)
```

```{r}
chiasso <- read_rds("data/grid/chiasso.Rds")
```

```{r}
chiasso %>% 
  st_geometry() %>% 
  qtm(borders = "red", fill = NULL)
```

## swisscom grid

Tile definitions pulled from API using `query_postal_codes_heatmaps_api.py`.  

```{r}
chansy_grid <- fromJSON("data/swisscom/chansy_grid.json")
chansy_grid <- flatten(chansy_grid$tiles)

chiasso_grid <- fromJSON("data/swisscom/chiasso_grid.json")
chiasso_grid <- flatten(chiasso_grid$tiles)


chansy_grid_sf <- chansy_grid %>% 
  st_as_sf(coords = c("ll.x", "ll.y"), 
           crs = 4326,
           remove = FALSE) %>% 
  st_transform(21781) %>% 
  mutate(x = st_coordinates(.)[, 1],
         y = st_coordinates(.)[, 2])

chiasso_grid_sf <- chiasso_grid %>% 
  st_as_sf(coords = c("ll.x", "ll.y"), 
           crs = 4326,
           remove = FALSE) %>% 
  st_transform(21781) %>% 
  mutate(x = st_coordinates(.)[, 1],
         y = st_coordinates(.)[, 2])
```


```{r}
qtm(chansy_grid_sf)
qtm(chiasso_grid_sf)
```


```{r}
offset_swisscom <- 
  bind_rows(
    
  chansy_grid_sf %>% 
  st_drop_geometry() %>%
  summarise(min_x = min(x),
            min_y = min(y)) ,

  chiasso_grid_sf %>% 
  st_drop_geometry() %>%
  summarise(min_x = min(x),
            min_y = min(y)) 
  ) %>%
  summarise(min_x = min(min_x),
            min_y = min(min_y)) %>% 
  mutate(min_y = round(min_y)) %>% 
  st_as_sf(coords = c("min_x", "min_y"), 
           crs = 21781,
           remove = FALSE)

offset_bfs <- read_rds("data/BfS/statpop_20.Rds") %>% 
  summarise(min_x = min(X_KOORD),
            min_y = min(Y_KOORD)) %>% 
  st_as_sf(coords = c("min_x", "min_y"), 
           crs = 21781,
           remove = FALSE)
```

```{r}
tm_shape(offset_bfs) +
    tm_dots(col = "black") +
tm_shape(offset_swisscom) +
    tm_dots(col = "red")
```




